name: Test & deploy

on: 
  push:
     

jobs:
  run-shell-conmand:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: | 
          node -v
          npm -v
